---
title: "United States Seven-day COVID Deaths by State"
author: "Mark Sucato"
date: "9/22/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE,message=FALSE)
```

---

```{r}
library(tidyverse)
library(plotly)

data <- read.csv("COVID_data1.csv")

# https://covid.cdc.gov/covid-data-tracker/#cases_deathsper100klast7days
# downloaded 9/21/21 1622 EDT

data$hover <- with(data, paste(State, '<br>', "7-Day Death Rate:", SevenDayDeathPer, "per 100,000 people"))
borders <- list(color = toRGB("black"))
map_options <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
plot_ly(z = ~data$SevenDayDeathPer, text = ~data$hover, locations = ~data$Abr, 
        type = 'choropleth', locationmode = 'USA-states', 
        color = data$SevenDayDeathPer, colors = 'Reds', marker = list(line = borders)) %>%
  layout(title = '9/21/21 Seven-Day COVID Deaths per 100,000 people', geo = map_options, width="100%", height=600)
```


